controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui

api_login_check:
    path: /api/login
